[workspace]

members = [
    "wavesexchange_log",
    "wavesexchange_warp",
    "wavesexchange_topic",
    "wavesexchange_loaders",
    "wavesexchange_apis",
    "wavesexchange_liveness",
]

resolver = "2"
