[package]
name = "wavesexchange_loaders"
version = "0.2.1"
authors = ["Artem Sidorenko <kronos44_0@mail.ru>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.51"
cached = "0.26.2"
once_cell = "1.8.0"
dataloader = { git = "https://github.com/cksac/dataloader-rs", rev = "527933", default-features=false, features=["runtime-tokio"]}
thiserror = "1.0.30"
anymap = "0.12.1"

[dev-dependencies]
tokio = { version="1", features=["macros", "time"] }
