[package]
name = "wavesexchange_warp"
version = "0.4.0"
authors = ["Dmitry Shuranov <dvshur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
once_cell = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
warp = "0.2"
wavesexchange_log = { path = "../wavesexchange_log", version = "0.1" }
