[package]
name = "wavesexchange_warp"
version = "0.14.3"
authors = ["Dmitry Shuranov <dvshur@gmail.com>"]
edition = "2021"

[dependencies]
futures = "0.3"
lazy_static = "1.4.0"
once_cell = "1.4"
prometheus = { version = "0.13.1", features = ["process"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.8"
warp = "0.3"
wavesexchange_log = { path = "../wavesexchange_log", version = "0.5" }

[dev-dependencies]
tokio = { version = "1", features = ["macros", "time"] }
reqwest = "0.11.11"
